### PR TITLE
Updates strategy

### PR DESCRIPTION
**Pull request by Techlone**
I take changes from your fork but diffs from origin MT needs me too.
I can just take it from origin but I want to preserve the order of forks.
Any suggestions?

### CODE REVIEW

**Comment by Techlone** [comment]
@jaredlll08 are you here? :)

**Comment by jaredlll08** [comment]
Up to you, mine is more active but original is official

**Comment by Techlone** [comment]
>mine is more active

Then a question. How fast do you take a diff from original?

**Comment by jaredlll08** [comment]
Do you mean how often do I update from master? Usually as soon as something
changes in master that doesn't mess with my stuff

**Comment by Techlone** [comment]
>Do you mean how often do I update from master?

Yeah.. fast.. often... Sometimes my English isn't correct.
So can you merge the PR please?

**Comment by jaredlll08** [comment]
I was only replying via email, I had no idea this was a PR xD

**Pull request merged**
