### PR TITLE
Adds global variabled and disabled folders ect 

### PR DESCRIPTION
**Pull request by johnfg10**
from techlones version closes https://github.com/jaredlll08/CraftTweaker/issues/28

### CODE REVIEW

**Comment by jaredlll08** [comment]
I'm only going to accept this if it is OK with @Techlone

**Comment by johnfg12** [comment]
he says in the issue you can pull request it your self

**Comment by jaredlll08** [comment]
Yes, but I don't like his negativity towards it, like why didn't he make
the PR?

**Comment by johnfg12** [comment]
because he doesnt like the direction your taking craft tweaker im guessing

**Comment by johnfg12** [comment]
"wtf
What happened to CraftTweaker? Tons of strange commits. Uh. Fine.
I don't know how to resolve it... I won't make a PR. Just do what you want with iia-edition branch I don't care."

**Comment by jaredlll08** [comment]
Well ok then, I'm not going to accept this, mainly because there wouldn't
be anyone to support the code if there is a problem with it. @techlone, if
you have a problem, please speak to me about it :)

**Comment by Techlone** [comment]
I don't want do anything for MT3 because I think that ZenScript is a bad solution for scripting. ZS hasn't global vals and doesn't support global functions. Also it's peudo-dynamic lang. Compiling code is very complex. So I decided throw it.
@jaredlll08 
Pardon me. Your commits are not the reason of my decision.

**Comment by jaredlll08** [comment]
Ok, so I'm just confirming, this code has been tested, it works, and won't
cause issues with existing scripts, and most of all, you have 0 issues with
me accepting this PR

**Comment by johnfg12** [comment]
our mod pack team has tested and am now using it for the pack we have had 0 issues you can see our current set up which @kindlich has been working on here https://github.com/MyM-ModpackTeam/hypovolemia/tree/master/src/scripts

**Comment by jaredlll08** [comment]
I will look into it, but just remember that you are not allowed to
distribute copies of this mod without changing the name...

**Comment by bookerthegeek** [comment]
We don't redistribute it. It is only in use on the server. Would it need to be renamed their also as we are not redistributing to our players? If so I will do so asap.

**Comment by bookerthegeek** [comment]
Also hell yes to global variables!

**Comment by jaredlll08** [comment]
Look, I would prefer you don't redistribute the mod on a platform, like
curse, technic etc, if you do, you need to rename the mod so people done
come to me for help. A private server, as long as people know it is
modified, then go ahead.

**Comment by bookerthegeek** [comment]
Gotcha. Just so I know I explained it correctly, we are not redistributing it. The modified versions are only being used on server side.

**Comment by jaredlll08** [comment]
Yip, no problem there, also maybe give it to your players, would be a good
test :P

**Comment by bookerthegeek** [comment]
Gotcha,  will set that up tonight. 

Completely off topic, what are you working on lately? Also hit me up on irc if you get a chance.

**Comment by jaredlll08** [comment]
I'm taking a break from all tweaker things, modtweaker and minetweaker,
currently working on Fluxed-Crystals-3
Also I don't use irc anymore, join my discord :P
https://discord.gg/3VBK9ar

**Comment by Blue64** [comment]
I do agree about the Globals, if I could set my Indexed Item Array as Global Values, I totally would, because that'd save me SO much space in the overall File Size, and if I'm not mistaken, isn't there an Upper Limit to the processing capacity of a Script?

I would assume of course that the Capacity is somewhere around the same length as a Float/Double, which is relatively Galactic as far as Raw Text is concerned, until you realize that this entire Mod is built entirely around customization and personalization, which means it likely could meet that quota threefold, which is a problem that caught AE2 off guard (people were using AE2 to store Months to Years of Quarries, not to mention the whole `Bag inside a Bag inside a Bag [etc.]` NBT problem), so my questions are:
What exactly **_IS_** the Limit for the Compiler?
Is it better to have one gargantuan script? (limit-wise, clearly there's a performance edge there)
Would the limit be expanded by splitting the Script into multiple parts?

**Comment by jaredlll08** [comment]
the limit on script files are imposed via the JVM, the limitations can be found here:
https://docs.oracle.com/javase/specs/jvms/se8/jvms8.pdf
page 330 and onwards

**Comment by Blue64** [comment]
so, is it better to split, or not?

**Comment by jaredlll08** [comment]
Well that is up to you, some people like to split their scripts up into different mods, other's have it all in a single script.
If you run into the error you mentioned though, well take a look here
https://github.com/stanhebben/MineTweaker3/issues/212

**Comment by Blue64** [comment]
lol yeah, I read that one too, but my question was if splitting the scripts up would somewhat bypass that limit (clearly it's not infinite, as eventually you'll just run out of room, but the question is if that room is expanded by splitting the files up, eg. Compiler can't handle 1MB but can handle 10 sets of 250KB)

**Comment by jaredlll08** [comment]
Yip, splitting the files up would solve the issue

**Comment by jaredlll08** [comment]
ok I'm tired of seeing this here, it will not get it.

**Pull request closed without merging**
