### PR TITLE
[1.11.2] Fixed OreDict addition and removal

### LINKED ISSUE #142: Oredict doesn't clear when reloading
#### Intro:
When creating custom oredicts you might make mistakes. The current way CraftTweaker works forces you to restart the game if you make a mistake.

#### Issue Description:
When you reload a script, your custom oredicts aren't cleared. You'll have to remove each recipe individually to clear an oredict.

#### What happens:
Oredicts retain their added items when reloading. This is both visually with JEI and in crafting recipes.

#### What you expected to happen:
Oredicts should clear between reloads, since they will be cleared next time you load the game. This should only happen for custom oredicts. Alternatively, an oreDict.clear() method could be added which could be placed in the beginning of a script.

____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 2202
- Crafttweaker: 1.10.2-3.0.17

### PR DESCRIPTION
**Pull request by GoryMoon**
Fixed ore dict not being removed and added, also updated in JEI for searching.
Fixes #142 and mezz/JustEnoughItems#848

Also removed your left debug messages

### CODE REVIEW

**Comment by jaredlll08** [comment]
Thanks! Is it possible for you to implement this for the 1.12 branch as well?

**Comment by GoryMoon** [comment]
About finished with the 1.12 branch, will make a pull request for it and then I need to verify the addAll and mirror on this, didn't test those very well before

**Comment by GoryMoon** [comment]
I've now tested the addAll and mirror and fixed undoing of addAll so it should be ready to merge.

**Comment by WesCook** [comment]
Wow, thank you Gory.  This bug plagued me for months, and made testing large packs much more difficult.  Nice work in finally tracking it down!

**Comment by winnetrie83** [comment]
Would it be posseble to fix this also for 1.10.2?

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore.

**Pull request merged**
